const Map<String, List<String>> uzbekistanLocations = {
  'Andijon viloyati': [
    'Andijon shahri',
    'Andijon tumani',
    'Asaka',
    'Baliqchi',
    'Boz',
    'Buloqboshi',
    'Izboskan',
    'Jalaquduq',
    'Marhamat',
    'Paxtaobod',
    'Shahrixon',
    'Xojaobod',
  ],
  'Buxoro viloyati': [
    'Buxoro shahri',
    'Buxoro tumani',
    'Gijduvon',
    'Jondor',
    'Kogon',
    'Olot',
    'Peshku',
    'Qorako\'l',
    'Romitan',
    'Shofirkon',
    'Vobkent',
  ],
  'Farg\'ona viloyati': [
    'Farg\'ona shahri',
    'Beshariq',
    'Bog\'dod',
    'Buvayda',
    'Dang\'ara',
    'Farg\'ona tumani',
    'Oltiariq',
    'Qo\'qon',
    'Quva',
    'Rishton',
    'Toshloq',
    'Uchko\'prik',
    'Yozyovon',
  ],
  'Jizzax viloyati': [
    'Jizzax shahri',
    'Arnasoy',
    'Baxmal',
    'Do\'stlik',
    'Forish',
    'G\'allaorol',
    'Mirzacho\'l',
    'Paxtakor',
    'Yangiobod',
    'Zarbdor',
    'Zomin',
  ],
  'Namangan viloyati': [
    'Namangan shahri',
    'Chortoq',
    'Chust',
    'Kosonsoy',
    'Mingbuloq',
    'Namangan tumani',
    'Pop',
    'To\'raqo\'rg\'on',
    'Uchqo\'rg\'on',
    'Uychi',
    'Yangiqo\'rg\'on',
  ],
  'Navoiy viloyati': [
    'Navoiy shahri',
    'Karmana',
    'Konimex',
    'Navbahor',
    'Nurota',
    'Qiziltepa',
    'Tomdi',
    'Uchquduq',
    'Xatirchi',
    'Zarafshon',
  ],
  'Qashqadaryo viloyati': [
    'Qarshi shahri',
    'Chiroqchi',
    'Dehqonobod',
    'G\'uzor',
    'Kasbi',
    'Kitob',
    'Koson',
    'Mirishkor',
    'Muborak',
    'Nishon',
    'Qamashi',
    'Shahrisabz',
    'Yakkabog\'',
  ],
  'Qoraqalpog\'iston Respublikasi': [
    'Nukus shahri',
    'Amudaryo',
    'Beruniy',
    'Chimboy',
    'Ellikqal\'a',
    'Kegeyli',
    'Mo\'ynoq',
    'Qo\'ng\'irot',
    'Qorao\'zak',
    'Shumanay',
    'Taxiatosh',
    'To\'rtko\'l',
    'Xo\'jayli',
  ],
  'Samarqand viloyati': [
    'Samarqand shahri',
    'Bulung\'ur',
    'Ishtixon',
    'Jomboy',
    'Kattaqo\'rg\'on',
    'Narpay',
    'Nurobod',
    'Oqdaryo',
    'Pastdarg\'om',
    'Payariq',
    'Toyloq',
    'Urgut',
  ],
  'Sirdaryo viloyati': [
    'Guliston shahri',
    'Boyovut',
    'Guliston tumani',
    'Mirzaobod',
    'Oqoltin',
    'Sardoba',
    'Sayxunobod',
    'Sirdaryo',
    'Xovos',
    'Yangiyer',
  ],
  'Surxondaryo viloyati': [
    'Termiz shahri',
    'Angor',
    'Bandixon',
    'Boysun',
    'Denov',
    'Jarqo\'rg\'on',
    'Muzrabot',
    'Qiziriq',
    'Qumqo\'rg\'on',
    'Sariosiyo',
    'Sherobod',
    'Sho\'rchi',
    'Termiz tumani',
    'Uzun',
  ],
  'Toshkent viloyati': [
    'Toshkent shahri',
    'Nurafshon shahri',
    'Bekobod',
    'Bo\'ka',
    'Bo\'stonliq',
    'Chinoz',
    'Ohangaron',
    'Oqqo\'rg\'on',
    'Parkent',
    'Piskent',
    'Quyichirchiq',
    'Yangiyo\'l',
    'Yuqorichirchiq',
    'Zangiota',
  ],
  'Xorazm viloyati': [
    'Urganch shahri',
    'Bog\'ot',
    'Gurlan',
    'Hazorasp',
    'Khiva',
    'Qo\'shko\'pir',
    'Shovot',
    'Urganch tumani',
    'Xonqa',
    'Yangiariq',
    'Yangibozor',
  ],
};
