services:
  postgres:
    image: postgres:16-alpine
    container_name: taxi_postgres
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: taxi
      POSTGRES_DB: taxi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
